dataset_args:
  data_path: "datasets/coinrun/coinrun_dataset_jsons/release"
  sample_every_n_frames: 3
  sequence_length: 32
  resolution: 224
  bbox_smap_for_agent: False
  bbox_smap_for_monsters: False
  use_manual_annotation: True
  use_auto_annotation: False
  use_downsampled_trainset: False
  fixed_start_idx: False
  get_game_frame: True
  get_seg_map: False
  get_text_desc: True
  debug: False
datamodule_args:
  batch_size: 16
  num_workers: 4
  shuffle: False
  bert_text_transform: {}
  video_transform: {}
lightningmodule_args:
  logit_scale: 0.07
  logit_scale_max: 100.0
videoclip_args:
  text_pretrained: False
  text_trainable: False
  text_model_name: "distilbert-base-uncased"
  text_model_config: {}
  text_padding_value: 0
  video_pretrained: False
  video_trainable: False
  video_pretrain_path: "https://pytorch.s3.amazonaws.com/models/multimodal/mugen/S3D_kinetics400.pt"
  proj_out_dim: 256
  proj_dropout: 0.1
evaluation_args:
  accelerator: "auto"
  devices: 1
  checkpoint_path: "https://pytorch.s3.amazonaws.com/models/multimodal/mugen/videoclip_lightning_mugen.pt"
